# Generated by Django 5.0.7 on 2025-10-12 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0002_userprofile_address_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='razorpay', max_length=32)),
                ('event', models.CharField(blank=True, default='', max_length=64)),
                ('signature', models.CharField(blank=True, default='', max_length=256)),
                ('delivery_id', models.CharField(blank=True, max_length=128, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('raw_body', models.TextField(blank=True, default='')),
                ('processed_ok', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('matched_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='h2h.order')),
            ],
        ),
    ]
