# Generated by Django 5.0.7 on 2025-10-17 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0003_webhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('address', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. DT, ST, CT, HUT', max_length=12, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='base_includes',
            field=models.PositiveSmallIntegerField(default=1, help_text='People included in base price'),
        ),
        migrations.AddField(
            model_name='package',
            name='child_free_max_age',
            field=models.PositiveSmallIntegerField(default=5, help_text='Age <= this is free'),
        ),
        migrations.AddField(
            model_name='package',
            name='child_half_max_age',
            field=models.PositiveSmallIntegerField(default=15, help_text='Age <= this is half (and > free)'),
        ),
        migrations.AddField(
            model_name='package',
            name='child_half_multiplier',
            field=models.FloatField(default=0.5, help_text='Half-price multiplier (typically 0.5)'),
        ),
        migrations.AddField(
            model_name='package',
            name='extra_price_adult_inr',
            field=models.IntegerField(default=0, help_text='Extra price per additional ADULT. If 0, base price is used as extra adult price.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(help_text='Amount in paise'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('booking_open', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('guests', models.PositiveSmallIntegerField(default=1, help_text='Total people including the primary person')),
                ('guest_ages', models.JSONField(blank=True, help_text='List of ages for EXTRA guests only', null=True)),
                ('extra_adults', models.PositiveSmallIntegerField(default=0)),
                ('extra_children_half', models.PositiveSmallIntegerField(default=0)),
                ('extra_children_free', models.PositiveSmallIntegerField(default=0)),
                ('blood_group', models.CharField(blank=True, default='', max_length=5)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('pricing_total_inr', models.IntegerField(blank=True, null=True)),
                ('pricing_breakdown', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='h2h.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='h2h.event')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='h2h.property')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='h2h.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('label', models.CharField(help_text='Visible code/number for the unit (unique per property)', max_length=40)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('features', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HOLD', 'Hold'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='h2h.property')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='h2h.unittype')),
            ],
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='h2h.event')),
            ],
            options={
                'ordering': ['order', 'date'],
                'unique_together': {('event', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='h2h.booking')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='h2h.unit')),
            ],
            options={
                'unique_together': {('booking', 'unit')},
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'unit_type', 'category', 'status'], name='h2h_unit_propert_39c7de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'label')},
        ),
    ]
