# Generated by Django 5.0.7 on 2025-10-18 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0004_property_unittype_package_base_includes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='NO OF TENT / total units for this slice')),
                ('capacity_per_unit', models.PositiveSmallIntegerField(default=1, help_text='PEOPLE SHARE PER ROOM')),
                ('facility', models.TextField(blank=True, default='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rows', to='h2h.property')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_rows', to='h2h.unittype')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'unit_type', 'category'], name='h2h_invento_propert_4c2cf5_idx')],
                'unique_together': {('property', 'unit_type', 'category')},
            },
        ),
    ]
