# Generated by Django 5.0.7 on 2025-10-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0005_inventoryrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promo_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_discount_inr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Case-insensitive', max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent %'), ('FLAT', 'Flat INR')], max_length=10)),
                ('value', models.PositiveIntegerField(help_text='If PERCENT, 1–100; if FLAT, INR amount')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='h2h_promoco_code_6c3979_idx')],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='h2h.promocode'),
        ),
    ]
