# Generated by Django 5.0.7 on 2025-10-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0006_booking_promo_breakdown_booking_promo_discount_inr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='companions',
            field=models.JSONField(blank=True, help_text='List of co-travellers excluding primary user', null=True),
        ),
    ]
