# Generated by Django 5.0.7 on 2025-10-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0007_booking_companions'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='allowed_unit_types',
            field=models.ManyToManyField(blank=True, help_text='If empty, fallback PACKAGE_UNITTYPE_MAP is used.', related_name='packages', to='h2h.unittype'),
        ),
    ]
