# Generated by Django 5.0.7 on 2025-10-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0009_alter_booking_property_alter_booking_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='primary_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
