# Generated by Django 5.0.7 on 2025-10-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0010_booking_primary_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='primary_meal_preference',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan'), ('JAIN', 'Jain'), ('OTHER', 'Other / Unspecified')], default='NON_VEG', max_length=10),
        ),
    ]
