# Generated by Django 5.0.7 on 2025-10-26 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0011_booking_primary_meal_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='primary_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Age of the primary guest in years', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
