# Generated by Django 5.0.7 on 2025-10-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0012_booking_primary_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='promo_active',
            field=models.BooleanField(default=True, help_text='If OFF, promo codes cannot be applied to this package.'),
        ),
    ]
