# Generated by Django 5.0.7 on 2025-10-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0013_package_promo_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sightseeing_opt_in_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sightseeing_requested_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SightseeingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveSmallIntegerField(default=1)),
                ('participants', models.JSONField(blank=True, help_text='Optional snapshot of names/genders/meals', null=True)),
                ('pay_at_venue', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sightseeing', to='h2h.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightseeing_regs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
