# Generated by Django 5.0.7 on 2025-10-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0014_booking_sightseeing_opt_in_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sightseeing_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
