# Generated by Django 5.0.7 on 2025-10-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0015_booking_sightseeing_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
