# Generated by Django 5.0.7 on 2025-11-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0016_allocation_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Supabase public URL or signed URL for this image', max_length=500)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower values appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='h2h.package')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
