# Generated by Django 5.2.9 on 2025-12-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h2h', '0017_packageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.IntegerField(default=0, help_text='Total INR paid so far (sum of successful orders)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='h2h.booking'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('ADVANCE', 'Advance Payment'), ('BALANCE', 'Balance Payment'), ('REFUND', 'Refund')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PARTIAL', 'Partially Paid'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
